#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [[ -f "$HOME/.hermes/.env" ]]; then
  set -a
  source "$HOME/.hermes/.env"
  set +a
fi

export HERMES_WEB_PROJECT_ROOT="${HERMES_WEB_PROJECT_ROOT:-$PROJECT_ROOT}"
export HERMES_WEB_BIND_HOST="${HERMES_WEB_BIND_HOST:-127.0.0.1}"
export HERMES_WEB_FRONTEND_HOST="${HERMES_WEB_FRONTEND_HOST:-$HERMES_WEB_BIND_HOST}"
export HERMES_WEB_FRONTEND_PORT="${HERMES_WEB_FRONTEND_PORT:-8793}"
export HERMES_WEB_BACKEND_HOST="${HERMES_WEB_BACKEND_HOST:-$HERMES_WEB_BIND_HOST}"
export HERMES_WEB_BACKEND_PORT="${HERMES_WEB_BACKEND_PORT:-8791}"
export COPILOTKIT_RUNTIME_HOST="${COPILOTKIT_RUNTIME_HOST:-$HERMES_WEB_BIND_HOST}"
export COPILOTKIT_RUNTIME_PORT="${COPILOTKIT_RUNTIME_PORT:-8794}"
export HERMES_WEB_API_PREFIX="${HERMES_WEB_API_PREFIX:-/api}"
export HERMES_WEB_FRONTEND_URL="${HERMES_WEB_FRONTEND_URL:-http://${HERMES_WEB_FRONTEND_HOST}:${HERMES_WEB_FRONTEND_PORT}/}"
export HERMES_WEB_FRONTEND_BACKEND_BASE="${HERMES_WEB_FRONTEND_BACKEND_BASE:-http://${HERMES_WEB_BACKEND_HOST}:${HERMES_WEB_BACKEND_PORT}}"
export HERMES_WEB_BACKEND_API="${HERMES_WEB_BACKEND_API:-${HERMES_WEB_FRONTEND_BACKEND_BASE}${HERMES_WEB_API_PREFIX}}"
export HERMES_WEB_MODE="${HERMES_WEB_MODE:-hermes-api}"
export HERMES_WEB_COPILOTKIT_RUNTIME_BASE_URL="${HERMES_WEB_COPILOTKIT_RUNTIME_BASE_URL:-http://${COPILOTKIT_RUNTIME_HOST}:${COPILOTKIT_RUNTIME_PORT}}"
export VITE_COPILOTKIT_RUNTIME_URL="${VITE_COPILOTKIT_RUNTIME_URL:-${HERMES_WEB_API_PREFIX}/copilotkit}"
export HERMES_WEB_CORS_ALLOW_ORIGIN="${HERMES_WEB_CORS_ALLOW_ORIGIN:-http://${HERMES_WEB_FRONTEND_HOST}:${HERMES_WEB_FRONTEND_PORT},http://localhost:${HERMES_WEB_FRONTEND_PORT}}"
if [[ -n "${HERMES_WEB_PUBLIC_ORIGINS:-}" ]]; then
  export HERMES_WEB_CORS_ALLOW_ORIGIN="${HERMES_WEB_CORS_ALLOW_ORIGIN},${HERMES_WEB_PUBLIC_ORIGINS}"
fi
export COPILOTKIT_RUNTIME_ALLOWED_ORIGINS="${COPILOTKIT_RUNTIME_ALLOWED_ORIGINS:-$HERMES_WEB_CORS_ALLOW_ORIGIN}"
export HERMES_WEB_HERMES_API_BASE_URL="${HERMES_WEB_HERMES_API_BASE_URL:-http://127.0.0.1:8642/v1}"
export HERMES_WEB_HERMES_API_AUTH_MODE="${HERMES_WEB_HERMES_API_AUTH_MODE:-bearer}"
export HERMES_WEB_HERMES_API_KEY="${HERMES_WEB_HERMES_API_KEY:-${API_SERVER_KEY:-}}"
export HERMES_WEB_HERMES_API_MODEL="${HERMES_WEB_HERMES_API_MODEL:-openrouter/owl-alpha}"
export GIGACHAT_ADAPTER_HOST="${GIGACHAT_ADAPTER_HOST:-127.0.0.1}"
export GIGACHAT_ADAPTER_PORT="${GIGACHAT_ADAPTER_PORT:-8795}"
export GIGACHAT_ADAPTER_OAUTH_URL="${GIGACHAT_ADAPTER_OAUTH_URL:-https://ngw.devices.sberbank.ru:9443/api/v2/oauth}"
export GIGACHAT_ADAPTER_API_BASE_URL="${GIGACHAT_ADAPTER_API_BASE_URL:-https://api.giga.chat/v1}"
export GIGACHAT_ADAPTER_SCOPE="${GIGACHAT_ADAPTER_SCOPE:-GIGACHAT_API_B2B}"
export GIGACHAT_ADAPTER_TIMEOUT_SECONDS="${GIGACHAT_ADAPTER_TIMEOUT_SECONDS:-60}"
export GIGACHAT_ADAPTER_VERIFY_SSL="${GIGACHAT_ADAPTER_VERIFY_SSL:-1}"
export GIGACHAT_ADAPTER_TOKEN_SKEW_SECONDS="${GIGACHAT_ADAPTER_TOKEN_SKEW_SECONDS:-60}"
export GIGACHAT_ADAPTER_CA_CERT_FILE="${GIGACHAT_ADAPTER_CA_CERT_FILE:-$HOME/.hermes/certs/gigachat/russian-trusted-ca-bundle.crt}"
export HERMES_WEB_REASONING_MODEL="${HERMES_WEB_REASONING_MODEL:-deepseek/deepseek-r1-0528}"
export HERMES_WEB_REASONING_ROUTING_ENABLED="${HERMES_WEB_REASONING_ROUTING_ENABLED:-1}"
export HERMES_WEB_REASONING_MANUAL_ONLY="${HERMES_WEB_REASONING_MANUAL_ONLY:-0}"
export HERMES_WEB_REASONING_ENABLED="${HERMES_WEB_REASONING_ENABLED:-1}"
export HERMES_WEB_REASONING_DAILY_MAX_REQUESTS="${HERMES_WEB_REASONING_DAILY_MAX_REQUESTS:-60}"
export HERMES_WEB_REASONING_DAILY_MAX_PER_USER="${HERMES_WEB_REASONING_DAILY_MAX_PER_USER:-10}"
export HERMES_WEB_REASONING_DAILY_MAX_COST_USD="${HERMES_WEB_REASONING_DAILY_MAX_COST_USD:-2.5}"
export HERMES_WEB_REASONING_COST_FALLBACK_USD="${HERMES_WEB_REASONING_COST_FALLBACK_USD:-0.20}"
export COPILOTKIT_RUNTIME_BASE_URL="${COPILOTKIT_RUNTIME_BASE_URL:-$HERMES_WEB_HERMES_API_BASE_URL}"
export COPILOTKIT_RUNTIME_API_KEY="${COPILOTKIT_RUNTIME_API_KEY:-${API_SERVER_KEY:-${HERMES_WEB_HERMES_API_KEY:-}}}"
export COPILOTKIT_RUNTIME_MODEL="${COPILOTKIT_RUNTIME_MODEL:-${HERMES_WEB_HERMES_API_MODEL:-openrouter/owl-alpha}}"
export HERMES_WEB_SMOKE_FILE="${HERMES_WEB_SMOKE_FILE:-$PROJECT_ROOT/tmp/smoke-note.txt}"
